### PR TITLE
JakartaDestination: make class and fromJavax method public

### PR DESCRIPTION
**Pull request by ligfx**

### CODE REVIEW

**Comment by marschall** [comment]
Thank you for your contribution. A few questions to better understand your requirements:

- What is your use case? Something similar to #3? I.e. you have a queue or topic in JNDI and want to adapt it?
- It's a bit awkward to have an `abstract` class public just for a `static` method. Would a `public static` method in `Wrapper` work as well?
- What is the reason for switching from `JMSException` to `ClassCastException` in `JakartaDestination#fromJavax(Destination)` and the follow up change in `JakartaJMSProducer#getJMSReplyTo()`?
- What is the reason for the `null` handling in? Do you have messages or producers with either destination or reply to `null`?

**Comment by ligfx** [comment]
Hi @marschall!

> What is your use case? Something similar to https://github.com/marschall/jakarta-jms-adapter/issues/3? I.e. you have a queue or topic in JNDI and want to adapt it?

Yep, exactly. Getting destinations from JNDI and needing to adapt those to Jakarta.

> It's a bit awkward to have an abstract class public just for a static method. Would a public static method in Wrapper work as well?

Sure, that would work fine. I thought JakartaDestination made the most sense though and was consistent with JakartaConnectionFactory — having `Wrapper.fromJavaxDestination` isn't quite as clear IMO.

> What is the reason for switching from JMSException to ClassCastException in JakartaDestination#fromJavax(Destination) and the follow up change in JakartaJMSProducer#getJMSReplyTo()?

Two reasons: (1) `JMSException` taints all callers, which have to either handle it or mark as throwing it and (2) it's conceptually not really a JMSException, as it doesn't happen in the JMS subsystem. It's just a failure to wrap the class (e.g. a ClassCast). In the code I'm working on, the access to JNDI and getting destinations doesn't handle JMSExceptions because it's not actually doing anything with JMS, just getting objects. It raises red flags to handle JMSExceptions there.

> What is the reason for the null handling in? Do you have messages or producers with either destination or reply to null?

Yes, messages with null reply-to addresses. This was to fix errors caused by https://github.com/marschall/jakarta-jms-adapter/blob/6829d244f2cf3161f812a4ac26a00b1cda2b7c68/src/main/java/com/github/marschall/jakartajmsadapter/JakartaMessage.java#L95

**Comment by marschall** [comment]
Thank you. I went for a slightly different approach in #5. I will release to Maven Central tomorrow.

**Comment by marschall** [comment]
There was an issue with the 1.4.0 release, 1.4.1 is the one to make it to Maven Central.

**Pull request closed without merging**
